  maven:
    # Run pre-built maven image from docker library
    image: maven:3.8.7-eclipse-temurin-11-alpine
    volumes:
      - ${HOME}/.m2/settings.xml:/usr/share/maven/ref/settings.xml 
      - ${HOME}/.m2:/root/.m2
